<?php

namespace App\Tests;

use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase;
use App\Entity\Author;
use Hautelook\AliceBundle\PhpUnit\RefreshDatabaseTrait;

class AuthorsTest extends ApiTestCase
{
    // This trait provided by HautelookAliceBundle will take care of refreshing the database content to a known state before each test
    use RefreshDatabaseTrait;

    public function testGetCollection(): void
    {
        // The client implements Symfony HttpClient's `HttpClientInterface`, and the response `ResponseInterface`
        $response = static::createClient()->request('GET', '/authors');

        $this->assertResponseIsSuccessful();
        // Asserts that the returned content type is JSON-LD (the default)
        $this->assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');

        // Asserts that the returned JSON is a superset of this one
        $this->assertJsonContains([
            '@context' => '/contexts/Author',
            '@id' => '/authors',
            '@type' => 'hydra:Collection',
            'hydra:totalItems' => 100,
            'hydra:view' => [
                '@id' => '/authors?page=1',
                '@type' => 'hydra:PartialCollectionView',
                'hydra:first' => '/authors?page=1',
                'hydra:last' => '/authors?page=4',
                'hydra:next' => '/authors?page=2',
            ],
        ]);

        // Because test fixtures are automatically loaded between each test, you can assert on them
        $this->assertCount(30, $response->toArray()['hydra:member']);

        // Asserts that the returned JSON is validated by the JSON Schema generated for this resource by API Platform
        // This generated JSON Schema is also used in the OpenAPI spec!
        $this->assertMatchesResourceCollectionJsonSchema(Author::class);
    }

    public function testCreateAuthor(): void
    {
        $response = static::createClient()->request('POST', '/authors', ['json' => [
            'firstname' => 'Tom',
            'lastname' => 'Sawyer',
        ]]);

        $this->assertResponseStatusCodeSame(201);
        $this->assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');
        $this->assertJsonContains([
            '@context' => '/contexts/Author',
            '@type' => 'Author',
            'firstname' => 'Tom',
            'lastname' => 'Sawyer',
            'articles_id' => [],
        ]);
        $this->assertMatchesRegularExpression('~^/authors/\d+$~', $response->toArray()['@id']);
        $this->assertMatchesResourceItemJsonSchema(Author::class);
    }

    public function testCreateInvalidAuthor(): void
    {
        static::createClient()->request('POST', '/authors', ['json' => [
            'lastname' => 3,
        ]]);

        $this->assertResponseStatusCodeSame(422);
        $this->assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');

        $this->assertJsonContains([
            '@context' => '/contexts/ConstraintViolationList',
            '@type' => 'ConstraintViolationList',
            'hydra:title' => 'An error occurred',
            'hydra:description' => 'firstname: This value should be a string type and can\'t be null.
lastname: This value should be a string type.',
        ]);
    }

    public function testUpdateAuthor(): void
    {
        $client = static::createClient();
        // findIriBy allows to retrieve the IRI of an item by searching for some of its properties.
        // ISBN 9786644879585 has been generated by Alice when loading test fixtures.
        // Because Alice use a seeded pseudo-random number generator, we're sure that this ISBN will always be generated.
        $iri = $this->findIriBy(Author::class, ['firstname' => 'Tom']);

        $client->request('PUT', $iri, ['json' => [
            'firstname' => 'updated firstname',
        ]]);

        $this->assertResponseIsSuccessful();
        $this->assertJsonContains([
            '@id' => $iri,
            'firstname' => 'updated firstname',
            'lastname' => 'Sawyer',
        ]);
    }

    public function testDeleteAuthor(): void
    {
        $client = static::createClient();
        $iri = $this->findIriBy(Author::class, ['firstname' => 'updated firstname']);

        $client->request('DELETE', $iri);

        $this->assertResponseStatusCodeSame(204);
        $this->assertNull(
            // Through the container, you can access all your services from the tests, including the ORM, the mailer, remote API clients...
            static::$container->get('doctrine')->getRepository(Author::class)->findOneBy(['firstname' => 'updated firstname'])
        );
    }
}